import React from 'react';

export enum Ranks {
  WHITE = 1,
  ORANGE = 2,
  BLUE = 3,
  YELLOW = 4,
  GREEN = 5,
  BROWN = 6,
  SHODAN = 7,
  NIDAN = 8,
  SANDAN = 9,
  YONDAN = 10,
}

export enum KataNames {
  Taikyoku_Sono_Ichi = 'Taikyoku Sono Ichi',
  Taikyoku_Sono_Ni = 'Taikyoku Sono Ni',
  Sokugi_Taikyoku_Sono_Ichi = 'Sokugi Taikyoku Sono Ichi',
  Taikyoku_Sono_San = 'Taikyoku Sono San',
  Sokugi_Taikyoku_Sono_Ni = 'Sokugi Taikyoku Sono Ni',
  Sokugi_Taikyoku_Sono_San = 'Sokugi Taikyoku Sono San',
  Pinan_Sono_Ichi = 'Pinan Sono Ichi',
  Pinan_Sono_Ni = 'Pinan Sono Ni',
  Sanchin = 'Sanchin',
  Pinan_Sono_San = 'Pinan Sono San',
  Yantsu = 'Yantsu',
  Pinan_Sono_Yon = 'Pinan Sono Yon',
  Tsuki_No_Kata = 'Tsuki No Kata',
  Pinan_Sono_Go = 'Pinan Sono Go',
  Geksai_Sono_Ichi = 'Geksai Sono Ichi',
  Geksai_Sono_Ni = 'Geksai Sono Ni',
  Tekki_Sono_Ichi = 'Tekki Sono Ichi',
  Geksai_Sono_San = 'Geksai Sono San',
  Tekki_Sono_Ni = 'Tekki Sono Ni',
  Saifa = 'Saifa',
  Seienchin = 'Seienchin',
  Garyu = 'Garyu',
  Tekki_Sono_San = 'Tekki Sono San',
  Basai = 'Basai',
  Seipai = 'Seipai',
  Kanku = 'Kanku',
  Sushiho = 'Sushiho',
  Tensho = 'Tensho',
}

export const katas: any = {
  [Ranks.WHITE]: [
    KataNames.Taikyoku_Sono_Ichi,
    KataNames.Taikyoku_Sono_Ni,
    KataNames.Sokugi_Taikyoku_Sono_Ichi,
  ],
  [Ranks.ORANGE]: [
    KataNames.Taikyoku_Sono_San,
    KataNames.Sokugi_Taikyoku_Sono_Ni,
    KataNames.Sokugi_Taikyoku_Sono_San,
  ],
  [Ranks.BLUE]: [
    KataNames.Pinan_Sono_Ichi,
    KataNames.Pinan_Sono_Ni,
    KataNames.Sanchin,
  ],
  [Ranks.YELLOW]: [
    KataNames.Pinan_Sono_San,
    KataNames.Pinan_Sono_Yon,
    KataNames.Yantsu,
    KataNames.Tsuki_No_Kata,
  ],
  [Ranks.GREEN]: [
    KataNames.Pinan_Sono_Go,
    KataNames.Geksai_Sono_Ichi,
    KataNames.Geksai_Sono_Ni,
    KataNames.Tekki_Sono_Ichi,
    // 'Taikyoku Sono ichi Ura',
    // 'Taikyoku Sono Ni Ura',
    // 'Taikyoku Sono San Ura',
  ],
  [Ranks.BROWN]: [
    KataNames.Geksai_Sono_San,
    KataNames.Tekki_Sono_Ni,
    KataNames.Saifa,
    // 'Pinan Sono ichi Ura',
    // 'Pinan Sono Ni Ura',
    // 'Pinan Sono San Ura',
    // 'Pinan Sono Yon Ura',
    // 'Pinan Sono Go Ura',
  ],
  [Ranks.SHODAN]: [
    KataNames.Seienchin,
    KataNames.Garyu,
    KataNames.Tekki_Sono_San,
    KataNames.Basai,
  ],
  [Ranks.NIDAN]: [KataNames.Seipai],
  [Ranks.SANDAN]: [KataNames.Kanku],
  [Ranks.YONDAN]: [KataNames.Sushiho, KataNames.Tensho],
};
